apiVersion: v1
kind: Pod
metadata:
  name: kafka-python
  namespace: default
spec:
  containers:
  - image: ibmcom/kafka-python:latest
    imagePullPolicy: IfNotPresent
    name: python-sample
    env:
    - name: VCAP_SERVICES
      valueFrom:
          secretKeyRef:
            name: eventstreams-binding
            key: binding